/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrefixesRouteImport } from './routes/prefixes'
import { Route as GainsRouteImport } from './routes/gains'
import { Route as ComptesRouteImport } from './routes/comptes'
import { Route as BaremesRouteImport } from './routes/baremes'
import { Route as IndexRouteImport } from './routes/index'

const PrefixesRoute = PrefixesRouteImport.update({
  id: '/prefixes',
  path: '/prefixes',
  getParentRoute: () => rootRouteImport,
} as any)
const GainsRoute = GainsRouteImport.update({
  id: '/gains',
  path: '/gains',
  getParentRoute: () => rootRouteImport,
} as any)
const ComptesRoute = ComptesRouteImport.update({
  id: '/comptes',
  path: '/comptes',
  getParentRoute: () => rootRouteImport,
} as any)
const BaremesRoute = BaremesRouteImport.update({
  id: '/baremes',
  path: '/baremes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baremes': typeof BaremesRoute
  '/comptes': typeof ComptesRoute
  '/gains': typeof GainsRoute
  '/prefixes': typeof PrefixesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baremes': typeof BaremesRoute
  '/comptes': typeof ComptesRoute
  '/gains': typeof GainsRoute
  '/prefixes': typeof PrefixesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baremes': typeof BaremesRoute
  '/comptes': typeof ComptesRoute
  '/gains': typeof GainsRoute
  '/prefixes': typeof PrefixesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/baremes' | '/comptes' | '/gains' | '/prefixes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/baremes' | '/comptes' | '/gains' | '/prefixes'
  id: '__root__' | '/' | '/baremes' | '/comptes' | '/gains' | '/prefixes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaremesRoute: typeof BaremesRoute
  ComptesRoute: typeof ComptesRoute
  GainsRoute: typeof GainsRoute
  PrefixesRoute: typeof PrefixesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prefixes': {
      id: '/prefixes'
      path: '/prefixes'
      fullPath: '/prefixes'
      preLoaderRoute: typeof PrefixesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gains': {
      id: '/gains'
      path: '/gains'
      fullPath: '/gains'
      preLoaderRoute: typeof GainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comptes': {
      id: '/comptes'
      path: '/comptes'
      fullPath: '/comptes'
      preLoaderRoute: typeof ComptesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baremes': {
      id: '/baremes'
      path: '/baremes'
      fullPath: '/baremes'
      preLoaderRoute: typeof BaremesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaremesRoute: BaremesRoute,
  ComptesRoute: ComptesRoute,
  GainsRoute: GainsRoute,
  PrefixesRoute: PrefixesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
